### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by angeousta** [23rd/tdesktop#106]
### Is your feature request related to a problem?

I can't find the linux build

### Describe the solution you'd like

A linux build

### Describe alternatives you've considered

Searching for it but I didn't find it

### Additional context

64 bit

**Comment by 23rd** [comment]
Yeah, I'm looking for it every week too, but sadly I can't find anything. =(
In past I used the Github servers to build Linux binaries, but at some moment it became extremely large, so the Github servers couldn't handle it anymore. I'm looking for ways to build Linux binaries, unfortunately because of Docker and LTO it became more complicated than other platforms.

**Comment by angeousta** [comment]
Do you have a set of instructions (a .sh file) that one can run to build their own forkgram? with a readme on api keys I guess

**Comment by unia909** [comment]
Hello, the last version that was built for linux was [4.6.3](https://github.com/forkgram/tdesktop/releases/download/v4.6.3/Telegram.tar.xz). I'm waiting for the maintainer to build a newer version or a simple build instruction that requires 1-2 commands and at least less than 10GB of space.

**Comment by 23rd** [comment]
Okay. Please check out the version v4.9.3.

**Comment by 23rd** [comment]
Also, the previous v4.6.3 can be auto-updated to the latest.

**Comment by angeousta** [comment]
Can't you have a Github action to automatically build it and append it on releases?
