### ISSUE TITLE
"delete for everyone" option is not appear

### ISSUE THREAD

**Issue by mod098** [23rd/tdesktop#72]
### Steps to reproduce

1. right click a message in bot page
2. click delete

### Expected behaviour

there should be "delete for everyone" option and marked by default

### Actual behaviour

![image](https://user-images.githubusercontent.com/114498272/196246349-309c5554-f27d-4cf8-8608-c46e1c211236.png)

### Operating system

windows 10

### Version of Telegram Desktop

4.2.4

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Messages in chats with bots are unconditionally deleted for both sides, so there's no point in displaying the check box.

**Comment by zarEclEC** [comment]
Then why the message say "just for you"?
![immagine](https://user-images.githubusercontent.com/6240983/206508610-f87b4e79-fe21-477e-97be-e24b2f33ca89.png)

**Comment by 23rd** [comment]
Because you can't control a conversation of any bots. Once bots accept messages, they have a full control over them and can keep them forever locally, or even forward them to other chats, or even send them to third-party clouds.
Yes, the Telegram Desktop requests to the Telegram server to "revoke" the message for both sides, but in the reality no one can ever guarantee that the bot on their side loses the message.

**Comment by zarEclEC** [comment]
Will the deletion reach the bot as some kind of update?
